export const items = [
  {
    id: 1,
    nombre: 'Papel Aluminio Make',
    img: 'https://makehogar.com.ar/wp-content/uploads/2020/01/6195.jpg',
    marca: 'Make',
    stock: 10,
    precio: 255,
  },
  {
    id: 2,
    nombre: 'Papel Manteca Make',
    img: 'https://makehogar.com.ar/wp-content/uploads/2020/01/6330.jpg',
    marca: 'Make',
    stock: 10,
    precio: 315,
  },
  {
    id: 3,
    nombre: 'Film Adherente Make',
    img: 'https://makehogar.com.ar/wp-content/uploads/2020/01/6196.jpg',
    marca: 'Make',
    stock: 10,
    precio: 350,
  },
  {
    id: 4,
    nombre: 'Esponja acero 50gr Make',
    img: 'https://perfumeriaburbujas.com.ar/wp-content/uploads/esponjas/make-acero.jpg',
    marca: 'Make',
    stock: 255,
    precio: 70,
  },
  {
    id: 5,
    nombre: 'Matamoscas Make',
    img: 'https://makehogar.com.ar/wp-content/uploads/2020/01/6368.jpg',
    marca: 'Make',
    stock: 40,
    precio: 130,
  },
  {
    id: 6,
    nombre: 'Centrifugador de verduras Make',
    img: 'https://makehogar.com.ar/wp-content/uploads/2020/01/6772.jpg',
    marca: 'Make',
    stock: 5,
    precio: 680,
  },
];
